name: ohan_health_app
description: "A new Flutter project."
publish_to: 'none' # Prevents the package from being accidentally published to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1  # Updated to a more recent version
  image_picker: ^1.0.0
  file_picker: ^8.0.7
  font_awesome_flutter: ^10.1.0
  flutter_native_splash: ^2.2.14
  intl: ^0.19.0
  device_info_plus: ^10.1.2
  provider: ^6.0.3
  http: ^1.2.2 
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_crashlytics: ^4.0.4
  cloud_firestore: ^5.2.1
  cloud_functions: ^5.0.4
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.0.4
  google_sign_in: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/b.png
