// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwr1iqsYzBihYSAY9VtpiftAy-VGrtrbk',
    appId: '1:937730950461:web:faffee32813b278e78f154',
    messagingSenderId: '937730950461',
    projectId: 'ohanflutter',
    authDomain: 'ohanflutter.firebaseapp.com',
    storageBucket: 'ohanflutter.appspot.com',
    measurementId: 'G-VK9L855LGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjo1eWvfZqVuU7i2t37VU7lb4Fcg4Ji6g',
    appId: '1:937730950461:android:0184607705d5b3fd78f154',
    messagingSenderId: '937730950461',
    projectId: 'ohanflutter',
    storageBucket: 'ohanflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm2lDOFvSHBFW-sw4HpAhEbjHDZRKT40U',
    appId: '1:937730950461:ios:2093ec15d5120ffa78f154',
    messagingSenderId: '937730950461',
    projectId: 'ohanflutter',
    storageBucket: 'ohanflutter.appspot.com',
    iosClientId: '937730950461-03g3b9hutosld9lumrm0uss6jdv3gdoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ohanHealthApp',
  );

}